### ISSUE TITLE
New colormap issues

### ISSUE THREAD

**Issue by luisortizuriarte** [shueze/clim680#2]
It seems that by changing the normalization to a log scale, you've gained detail in some areas and lost some in others. In your previous plot, you had a lot of detail between 10-100 in the scale that is now lost, but added detail outside. You can play around with various options (adding new levels manually, adding more total levels, etc).

**Comment by pdirmeyer** [comment]
Please respond to this issue with a description of the changes you made. Then we can close the issue and change the grade.

**Comment by shueze** [comment]
Thank you. Because the data values mostly range from 10 to 100, and also has values over 1000, instead of using a regular scale or a log scale, I manually set the contour levels and colormap to make the plotting look detailed and nice.

**Comment by luisortizuriarte** [comment]
Closing this issue as it has been resolved.
