### ISSUE TITLE
Climatology plotting problems

### ISSUE THREAD

**Issue by shueze** [shueze/clim680#3]
I haven't figured out how to add coordinates to the dataset and interpolate to regular grids. I will try to do it later. Also, the loop thing at the end got an error and I'm figuring it out, but the plotting appears though.

**Comment by pdirmeyer** [comment]
As we discussed, you can use the class on [interpolating irregular grids](https://github.com/pdirmeyer/clim680-codes/blob/gh-pages/src/Arctic_Rean_Regrid.ipynb) as a guide to making your dataset geo-registered and plotable with coastlines. You will first have to add the latitudes and longitudes as new coordinate arrays to your dataframe, and then you can define a target grid that is regular in latitude and longitude to interpolate onto.

**Comment by shueze** [comment]
Thank you. The original dataset seemed too large for Jupyter notebook to handle, so I pre-processed the dataset, extracted the needed variables, and added latlon coordinates.

**Comment by pdirmeyer** [comment]
Good - you may close this issue.
