### ISSUE TITLE
Assignment 2: colorbar(s)

### ISSUE THREAD

**Issue by pdirmeyer** [shueze/clim680#4]
You can create a single colorbar for all 12 panels, instead of repeating the colorbar 12 times. This is done by adding a new plotting axis for the colorbar, as was done in [the lesson on multi-panel plotting](https://github.com/pdirmeyer/clim680-codes/blob/gh-pages/src/multipanel.ipynb)

**Comment by shueze** [comment]
Thank you. Done that.
