### ISSUE TITLE
Assignment 2: labeling

### ISSUE THREAD

**Issue by pdirmeyer** [shueze/clim680#5]
The figure needs more information. What is the quantity?  What are the units? What years are included in the climatology? The time period of each panel also needs to be labeled.

**Comment by shueze** [comment]
Done that. Thanks!

**Comment by pdirmeyer** [comment]
Much better. The labels above each panel are not clear, however. Are these hours? The string formatting appears to be incorrect. If you need to combine numbers and text in a string, there are several ways to do that.  The preferred way is to use "F-strings" - there are many resources on the web, but I find this [cheat sheet](https://cheatography.com/brianallan/cheat-sheets/python-f-strings-basics/) useful.

**Comment by shueze** [comment]
Changed titles to be title = f"UTC={2*i}~{2*i+1}". Thank you!
