### ISSUE TITLE
[Assignment 3] Code needs documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [shueze/clim680#7]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote!

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by shueze** [comment]
Added more documentation. Sorry for that.

**Comment by pdirmeyer** [comment]
This is better - you should use the markdown cells to describe the the overall flow of your notebook, and any ancillary information. Inside the code cells, you should put inline documentation to describe what individual lines or blocks of code are doing.

**Comment by shueze** [comment]
Thank you! I've added more documentation.

**Comment by luisortizuriarte** [comment]
This looks good! Thanks.
