### ISSUE TITLE
[Assignment 3] Plot clarity

### ISSUE THREAD

**Issue by pdirmeyer** [shueze/clim680#8]
Please define high, medium and low - give the ranges in the plot. A plot like this should be self-explanatory if possible.

Scientifically, what is this showing - what is interesting?
Are there any locations where PM gets higher when the area mean gets lower?

You do not need to do this for Assignment 3, but for your project it would be interesting to compare to a winter month, e.g., January, when the air pollution conditions are quite different.

**Comment by shueze** [comment]
Added ranges in the plot and some observations of the plot. Thank you!
